spring: 
  rabbitmq:
    host: 192.168.48.128
    port: 5672
    username: admin
    password: admin
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      name: user-service
      profile: dev
      
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka