spring:
  application:
    name: config-server
  rabbitmq:
    host: 192.168.77.129
    port: 5672
    username: admin
    password: admin  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shaoTimbleWolf/sp-config
          searchPaths: config
          #username: 
          #password: 
    
server:
  port: 6001
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
